#!/usr/bin/env zsh
# --------------------------------------------------------------------------
#   Enedos ZSH extension
# --------------------------------------------------------------------------

# Define exports
export ENEDOS_HELPERS_DIR="$HOME/enedos/helpers"
export ENEDOS_SCRIPTS_DIR="$ENEDOS_HELPERS_DIR/scripts"

# These need to be loaded first.
source $ENEDOS_SCRIPTS_DIR/logging
source $ENEDOS_SCRIPTS_DIR/docker

# Load other helpers.
source $ENEDOS_SCRIPTS_DIR/ohmyzsh
source $ENEDOS_SCRIPTS_DIR/portainer
