#!/usr/bin/env bash
# --------------------------------------------------------------------------
#   Scripts → Helpers → Docker
# --------------------------------------------------------------------------

# Load logging.
source $ENEDOS_ALIASES_DIR/logging


function docker_exec {
  PID=`docker ps | grep $1 | awk '{print $1}'`
  sudo docker exec -it $PID /bin/bash || error "Failed to exec into Docker container!"
}

function docker_get_container_name {
  NAME=`docker ps | grep $1 | awk '{print $2}'` || error "Failed to get Docker container PID!"
  echo $NAME
}

function docker_get_container_pid {
  PID=`docker ps | grep $1 | awk '{print $1}'` || error "Failed to get Docker container PID!"
  echo $PID
}

function docker_install {
  curl -sSL https://get.docker.com | sh || error "Failed to install Docker."
  sudo usermod -aG docker $USER || error "Failed to add user to the Docker usergroup."
  echo "Remember to logoff/reboot for the changes to take effect."
}

function docker_purge {
  sudo docker system prune --all --force || error "Failed to purge Docker system!"
}
