#!/usr/bin/env bash

# --------------------------------------------------------------------------
#   Nightly refresh
#   A collection of clean-up and maintenance tasks to be run nightly.
#   @see crontab
# --------------------------------------------------------------------------

#   Helpers
# ------------------------------------------------------------
function _send_log {
  echo "Last ran at $(date)" >> "/home/herupa/enedos/helpers/logs/crontab_$1.log"
}

#   Jobs
# ------------------------------------------------------------
function _prune_containers {
  docker container prune -f
  _send_log prune_containers
}

function _prune_images {
  docker image prune -f
  _send_log prune_images
}

function _prune_volumes {
  docker volume prune -f
  _send_log prune_volumes
}

function _find_manager_node {
  docker service update portainer_agent --force
  _send_log find_manager_node
}

function _refresh_mam {
  curl -c $HOME/mam.cookies -b $HOME/mam.cookies https://t.myanonamouse.net
}


#   Main
# ------------------------------------------------------------
function _run_worker_jobs {
  _prune_containers
  _prune_images
  _prune_volumes
}

function _run_manager_jobs {
  _prune_containers
  _prune_images
  _prune_volumes
  _find_manager_node
}

function _print_usage {
  printf "Usage: ..."
}

while getopts "gmw" flag; do
  case "${flag}" in
    g) _refresh_mam ;;
    m) _run_manager_jobs ;;
    w) _run_worker_jobs ;;
    *) _print_usage
      exit 1 ;;
  esac
done